"""Constants for the SoCal Gas integration."""
DOMAIN = "socalgas"
CONF_UPLOADED_FILE = "uploaded_file"
CONF_ACCOUNT_NAME = "account_name"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_ACCOUNT_NUMBER = "account_number"
CONF_METER_NUMBER = "meter_number"
CONF_LOOKBACK_DAYS = "lookback_days"
CONF_REFRESH_INTERVAL_HOURS = "refresh_interval_hours"
DEFAULT_REFRESH_INTERVAL_HOURS = 24
CONF_BROWSERLESS_URL = "browserless_url"
DEFAULT_BROWSERLESS_URL = "http://browserless:3000"
CONF_INITIAL_IMPORT_DONE = "initial_import_done"
